### ISSUE TITLE
Space leaks can result from stale registers and stack slots.

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#312] opened 2013-07-28 09:36 UTC
**Reported by: wdc  on Fri Oct 16 06:00:00 1998**
112 v0.34 (981016 / wdc)
Priority: medium
Category: TWOBIT / quality-of-implementation

Space leaks can result from stale registers and stack slots.

**Comment by WillClinger** [comment] 2015-01-19 01:02
This seems to be a duplicate of ticket #313.

**Closed by WillClinger** 2015-01-19 01:02 UTC
Labels: C: TWOBIT, C: twobit, duplicate, P: major, T: quality-of-implementation
