### ISSUE TITLE
com.apple.quarantine

### ISSUE THREAD

**Issue by orchid-hybrid** [larcenists/larceny#715] opened 2015-03-12 23:27 UTC
Hello!

I'm just trying to get larceny working from the source tarball here: http://www.larcenists.org/download.html

It bootstrapped like a dream but in setting up R7RS mode `(larceny:compile-r7rs-runtime)` I got a lot of errors like this:

```
Error: unhandled condition:
Compound condition has these components: 
#<record &assertion>
#<record &who>
    who : compile-library
#<record &message>
    message : "contains non-library code"
#<record &irritants>
    irritants : ("._original.sls")
```

These files have some odd content like: `com.apple.quarantine^@q/0000;54fb37fc;Firefox;|org.mozilla.firefox`.

A fix is to delete all these odd files:

```
find . -name '._*sls' -delete
find . -name '._*sld' -delete
```

**Comment by WillClinger** [comment] 2015-03-13 12:53
I am unable to reproduce this.  In particular, the `find` commands (without the `-delete`) come up empty for me.

The following information would be helpful:
  * which tarball did you download? (`.tar.gz` or `.zip`)
  * what kind of machine and operating system are you using?
  * which directories contain the problematic files?
  * who created those problematic files and when? (as reported by `ls -l`)

**Comment by orchid-hybrid** [comment] 2015-03-13 14:02
This tar gz file on GNU/Linux: http://www.larcenists.org/LarcenyReleases/larceny-0.98-src.tar.gz

If I just do `tar -xvf larceny-0.98-src.tar.gz > log.txt`, the log output is this: https://gist.github.com/orchid-hybrid/b566731949af00199ac8

I think mac os x must create these unwanted "._" files, and they are probably invisible when on that OS (I am guessing). It isn't a high priority issue but I thought I should note the fix incase anyone has the same problem.

Those files have a creation date of March 7 17:33 but everyone in the archive is owned by my user.

**Comment by WillClinger** [comment] 2015-03-13 15:16
Thank you!

It's fixed now.  I don't know why those files didn't show up on my Macintosh.  In the future, I'll take care to prepare this source distribution using Linux.

**Closed by WillClinger** 2015-03-13 15:16 UTC
Labels: bug, C: Other, P: major, R: fixed, T: defect
